### ISSUE TITLE
Build failure on !AMD64(missing jpeg dependency)

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/reddit-place-script-2022-snap#1]
```
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py): started
  Building wheel for Pillow (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [186 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.8

...stripped

      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-40c6j6m8/pillow_a50f37bb442a459aadd5cd4402f36b18/setup.py", line 989, in <module>
          setup(
        File "/build/reddit-place-script-2022/parts/main/install/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)

...stripped

          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-40c6j6m8/pillow_a50f37bb442a459aadd5cd4402f36b18/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
```

## Reference

* [[Installation — Pillow (PIL Fork) 9.1.0 documentation](https://pillow.readthedocs.io/en/stable/installation.html#external-libraries)](https://pillow.readthedocs.io/en/stable/installation.html#external-libraries)

**Comment by brlin-tw** [comment]
Fixed by revision 6c8a4e2d88af5dc2d40f407a822ee5a16d5d08c8
